// Generated by Wrangler by running `wrangler types`

interface Env {
	SUPABASE_URL: string;
	SUPABASE_ANON_KEY: string;
	RESEND_API_KEY: string;
	CLOUDFLARE_TURNSTILE_SITE_KEY: string;
	CLOUDFLARE_TURNSTILE_SECRET_KEY: string;
}
